refactor: lazarus 1.4 -> 1.6
Upgrade the project to lazarus 1.6 with FPC 3.0

Fix compilation error:
DateTimeStr: UTF8String -> String

Fix compilation error:
add extra variable TrackerStrLoop

Fix deprecated function use in FileUtil
switch to LazFileUtils